//MENU
export const LOAD_MENU_REQUEST = "LOAD_MENU_REQUEST"
export const LOAD_MENU_FAIL = "LOAD_MENU_FAIL"
export const LOAD_MENU_SUCCESS = "LOAD_MENU_SUCCESS"

//PAGE1
//Load
export const PAGE1_LOAD_REQUEST = "PAGE1_LOAD_REQUEST"
export const PAGE1_LOAD_FAIL = "PAGE1_LOAD_FAIL"
export const PAGE1_LOAD_SUCCESS = "PAGE1_LOAD_SUCCESS"
//Pagination
export const PAGE1_NEXT = "PAGE1_NEXT"
export const PAGE1_PREVIOUS = "PAGE1_PREVIOUS"